DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE books (
  id SERIAL PRIMARY KEY NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  pages INTEGER NOT NULL DEFAULT 0,
  cover_url VARCHAR(255) NOT NULL DEFAULT 'https://i.imgur.com/ovb6fkL.png'
);